/**
 * Session summary lookup for the project/recent cards. Reads the AI labels already
 * stored in the index (generated by lib/enrich.ts via the local `claude` CLI) — no
 * Anthropic SDK, no API key. Falls back to the first user message when a session
 * hasn't been labeled yet.
 */
import { loadIndex } from './index-store';

export type SessionSummary = {
  topic: string;
  outcome: string;
  generatedAt: string;
  sourceMtime: number;
};

export async function getSummary(
  project: string,
  sessionId: string,
  _jsonlMtime: number
): Promise<SessionSummary | { error: string }> {
  const records = await loadIndex();
  const rec = records.get(`${project}__${sessionId}`);
  if (!rec) return { error: 'not-indexed' };
  if (!rec.title && !rec.summary) {
    // indexed but not labeled yet — surface the fallback title so cards aren't empty
    return {
      topic: rec.fallbackTitle,
      outcome: '',
      generatedAt: rec.indexedAt,
      sourceMtime: rec.mtime,
    };
  }
  return {
    topic: rec.title ?? rec.fallbackTitle,
    outcome: rec.summary ?? '',
    generatedAt: rec.indexedAt,
    sourceMtime: rec.mtime,
  };
}

export async function getCachedSummary(project: string, sessionId: string): Promise<SessionSummary | null> {
  const result = await getSummary(project, sessionId, 0);
  return 'error' in result ? null : result;
}
